// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcccgwmywfikquappbfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjY2Nnd215d2Zpa3F1YXBwYmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzc5MjksImV4cCI6MjA2MzkxMzkyOX0.9IvFoRaa4hQushhXtOfgPqo-bSPUX-F26CEQ07LU9AE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);